### ISSUE TITLE
one issue in your program

### ISSUE THREAD

**Issue by akshitha123hub** [anandhu2231/sec_hello#6]
![Screenshot_20230109_155710](https://user-images.githubusercontent.com/121024936/211302370-61e93255-02d2-4843-a86b-abfda22889b0.png)
haiii anandhu while i try to enter a string instead of number it's shows me error, yes this code is for calculation, but if a user try to enter a string instead of number consider that case also and add some code for handling that case, just check the user input if it is a string then display some messg like that

**Comment by anandhu2231** [comment]
Yha i looked on the issue so currently closing the issue.
